import axios from "axios";

const placeholder = {
  status: {
    timestamp: "2022-06-27T18:26:24.905Z",
    error_code: 0,
    error_message: null,
    elapsed: 21,
    credit_count: 1,
    notice: null,
  },
  data: {
    1: {
      id: 1,
      name: "Bitcoin",
      symbol: "BTC",
      category: "coin",
      description:
        "Bitcoin (BTC) is a cryptocurrency . Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,078,631. The last known price of Bitcoin is 20,843.72399471 USD and is down -1.58 over the last 24 hours. It is currently trading on 9588 active market(s) with $20,744,319,264.13 traded over the last 24 hours. More information can be found at https://bitcoin.org/.",
      slug: "bitcoin",
      logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
      subreddit: "bitcoin",
      notice: "",
      tags: [
        "mineable",
        "pow",
        "sha-256",
        "store-of-value",
        "state-channel",
        "coinbase-ventures-portfolio",
        "three-arrows-capital-portfolio",
        "polychain-capital-portfolio",
        "binance-labs-portfolio",
        "blockchain-capital-portfolio",
        "boostvc-portfolio",
        "cms-holdings-portfolio",
        "dcg-portfolio",
        "dragonfly-capital-portfolio",
        "electric-capital-portfolio",
        "fabric-ventures-portfolio",
        "framework-ventures-portfolio",
        "galaxy-digital-portfolio",
        "huobi-capital-portfolio",
        "alameda-research-portfolio",
        "a16z-portfolio",
        "1confirmation-portfolio",
        "winklevoss-capital-portfolio",
        "usv-portfolio",
        "placeholder-ventures-portfolio",
        "pantera-capital-portfolio",
        "multicoin-capital-portfolio",
        "paradigm-portfolio",
      ],
      "tag-names": [
        "Mineable",
        "PoW",
        "SHA-256",
        "Store Of Value",
        "State Channel",
        "Coinbase Ventures Portfolio",
        "Three Arrows Capital Portfolio",
        "Polychain Capital Portfolio",
        "Binance Labs Portfolio",
        "Blockchain Capital Portfolio",
        "BoostVC Portfolio",
        "CMS Holdings Portfolio",
        "DCG Portfolio",
        "DragonFly Capital Portfolio",
        "Electric Capital Portfolio",
        "Fabric Ventures Portfolio",
        "Framework Ventures Portfolio",
        "Galaxy Digital Portfolio",
        "Huobi Capital Portfolio",
        "Alameda Research Portfolio",
        "a16z Portfolio",
        "1Confirmation Portfolio",
        "Winklevoss Capital Portfolio",
        "USV Portfolio",
        "Placeholder Ventures Portfolio",
        "Pantera Capital Portfolio",
        "Multicoin Capital Portfolio",
        "Paradigm Portfolio",
      ],
      "tag-groups": [
        "OTHERS",
        "ALGORITHM",
        "ALGORITHM",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
        "CATEGORY",
      ],
      urls: {
        website: ["https://bitcoin.org/"],
        twitter: [],
        message_board: ["https://bitcointalk.org"],
        chat: [],
        facebook: [],
        explorer: [
          "https://blockchain.coinmarketcap.com/chain/bitcoin",
          "https://blockchain.info/",
          "https://live.blockcypher.com/btc/",
          "https://blockchair.com/bitcoin",
          "https://explorer.viabtc.com/btc",
        ],
        reddit: ["https://reddit.com/r/bitcoin"],
        technical_doc: ["https://bitcoin.org/bitcoin.pdf"],
        source_code: ["https://github.com/bitcoin/bitcoin"],
        announcement: [],
      },
      platform: null,
      date_added: "2013-04-28T00:00:00.000Z",
      twitter_username: "",
      is_hidden: 0,
      date_launched: null,
      contract_address: [],
      self_reported_circulating_supply: null,
      self_reported_tags: null,
      self_reported_market_cap: null,
    },
    2: {
      id: 2,
      name: "Litecoin",
      symbol: "LTC",
      category: "coin",
      description:
        "Litecoin (LTC) is a cryptocurrency . Users are able to generate LTC through the process of mining. Litecoin has a current supply of 84,000,000 with 70,596,431.27791464 in circulation. The last known price of Litecoin is 55.88894988 USD and is down -3.48 over the last 24 hours. It is currently trading on 789 active market(s) with $461,676,124.84 traded over the last 24 hours. More information can be found at https://litecoin.org/.",
      slug: "litecoin",
      logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/2.png",
      subreddit: "litecoin",
      notice: "",
      tags: [
        "mineable",
        "pow",
        "scrypt",
        "medium-of-exchange",
        "binance-chain",
        "bnb-chain",
      ],
      "tag-names": [
        "Mineable",
        "PoW",
        "Scrypt",
        "Medium of Exchange",
        "Binance Chain",
        "BNB Chain",
      ],
      "tag-groups": [
        "OTHERS",
        "ALGORITHM",
        "ALGORITHM",
        "INDUSTRY",
        "PLATFORM",
        "PLATFORM",
      ],
      urls: {
        website: ["https://litecoin.org/"],
        twitter: ["https://twitter.com/LitecoinProject"],
        message_board: [
          "https://litecointalk.io/",
          "https://litecoin-foundation.org/",
        ],
        chat: ["https://telegram.me/litecoin"],
        facebook: [],
        explorer: [
          "https://blockchair.com/litecoin",
          "https://chainz.cryptoid.info/ltc/",
          "http://explorer.litecoin.net/chain/Litecoin",
          "https://ltc.tokenview.com/en",
          "https://bscscan.com/token/0x4338665cbb7b2485a8855a139b75d5e34ab0db94",
        ],
        reddit: ["https://reddit.com/r/litecoin"],
        technical_doc: [],
        source_code: ["https://github.com/litecoin-project/litecoin"],
        announcement: ["https://bitcointalk.org/index.php?topic=47417.0"],
      },
      platform: {
        id: "2502",
        name: "Huobi Token",
        slug: "huobi-token",
        symbol: "HT",
        token_address: "0xecb56cf772b5c9a6907fb7d32387da2fcbfb63b4",
      },
      date_added: "2013-04-28T00:00:00.000Z",
      twitter_username: "LitecoinProject",
      is_hidden: 0,
      date_launched: null,
      contract_address: [
        {
          contract_address: "0xecb56cf772b5c9a6907fb7d32387da2fcbfb63b4",
          platform: {
            name: "HECO",
            coin: {
              id: "2502",
              name: "Huobi Token",
              symbol: "HT",
              slug: "huobi-token",
            },
          },
        },
        {
          contract_address: "0x4338665cbb7b2485a8855a139b75d5e34ab0db94",
          platform: {
            name: "BNB Smart Chain (BEP20)",
            coin: { id: "1839", name: "BNB", symbol: "BNB", slug: "bnb" },
          },
        },
        {
          contract_address: "0x13e93721dc992b3e14333dbdb48c0e7ec55431c3",
          platform: {
            name: "Hoo Smart Chain",
            coin: {
              id: "15165",
              name: "Hoo Smart Chain",
              symbol: "HSC",
              slug: "hoo-smart-chain",
            },
          },
        },
      ],
      self_reported_circulating_supply: null,
      self_reported_tags: null,
      self_reported_market_cap: null,
    },
    3: {
      id: 3,
      name: "Namecoin",
      symbol: "NMC",
      category: "coin",
      description:
        "Namecoin (NMC) is a cryptocurrency . Users are able to generate NMC through the process of mining. Namecoin has a current supply of 14,736,400. The last known price of Namecoin is 1.36233149 USD and is down -1.03 over the last 24 hours. It is currently trading on 7 active market(s) with $7,301.18 traded over the last 24 hours. More information can be found at https://www.namecoin.org/.",
      slug: "namecoin",
      logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/3.png",
      subreddit: "namecoin",
      notice: "",
      tags: ["mineable", "pow", "sha-256", "platform"],
      "tag-names": ["Mineable", "PoW", "SHA-256", "Platform"],
      "tag-groups": ["OTHERS", "ALGORITHM", "ALGORITHM", "CATEGORY"],
      urls: {
        website: ["https://www.namecoin.org/"],
        twitter: ["https://twitter.com/Namecoin"],
        message_board: [],
        chat: ["https://www.namecoin.org/resources/chat/"],
        facebook: [],
        explorer: [
          "https://nmc.tokenview.com/",
          "https://www.namebrow.se/",
          "https://namecha.in/",
          "https://chainz.cryptoid.info/nmc/",
        ],
        reddit: ["https://reddit.com/r/namecoin"],
        technical_doc: ["https://www.namecoin.org/resources/whitepaper/"],
        source_code: ["https://github.com/namecoin"],
        announcement: ["https://bitcointalk.org/?topic=6017.0"],
      },
      platform: null,
      date_added: "2013-04-28T00:00:00.000Z",
      twitter_username: "Namecoin",
      is_hidden: 0,
      date_launched: null,
      contract_address: [],
      self_reported_circulating_supply: null,
      self_reported_tags: null,
      self_reported_market_cap: null,
    },
    4: {
      id: 4,
      name: "Terracoin",
      symbol: "TRC",
      category: "coin",
      description:
        "Terracoin (TRC) is a cryptocurrency launched in 2012. Users are able to generate TRC through the process of mining. Terracoin has a current supply of 22,935,396.430361. The last known price of Terracoin is 0.01652907 USD and is down -1.58 over the last 24 hours. It is currently trading on 2 active market(s) with $83.16 traded over the last 24 hours. More information can be found at http://www.terracoin.io/.",
      slug: "terracoin",
      logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/4.png",
      subreddit: "terracoin",
      notice: "",
      tags: ["mineable", "pow", "sha-256", "masternodes"],
      "tag-names": ["Mineable", "PoW", "SHA-256", "Masternodes"],
      "tag-groups": ["OTHERS", "ALGORITHM", "ALGORITHM", "CATEGORY"],
      urls: {
        website: ["http://www.terracoin.io/"],
        twitter: ["https://twitter.com/Terracoin_TRC"],
        message_board: ["https://medium.com/@clockuniverse"],
        chat: ["https://mattermost.terracoin.io/", "https://t.me/terracoin"],
        facebook: [],
        explorer: [
          "https://insight.terracoin.io/",
          "https://explorer.terracoin.io/chain/Terracoin",
        ],
        reddit: ["https://reddit.com/r/terracoin"],
        technical_doc: ["https://wiki.terracoin.io/view/Whitepaper"],
        source_code: ["https://github.com/terracoin"],
        announcement: ["https://bitcointalk.org/index.php?topic=1364146.0"],
      },
      platform: null,
      date_added: "2013-04-28T00:00:00.000Z",
      twitter_username: "Terracoin_TRC",
      is_hidden: 0,
      date_launched: "2012-10-26T00:00:00.000Z",
      contract_address: [],
      self_reported_circulating_supply: null,
      self_reported_tags: null,
      self_reported_market_cap: null,
    },
    5: {
      id: 5,
      name: "Peercoin",
      symbol: "PPC",
      category: "coin",
      description:
        "Peercoin (PPC) is a cryptocurrency . Users are able to generate PPC through the process of mining. Peercoin has a current supply of 27,618,902.62858635. The last known price of Peercoin is 0.28995206 USD and is down -1.46 over the last 24 hours. It is currently trading on 11 active market(s) with $2,696.99 traded over the last 24 hours. More information can be found at http://www.peercoin.net.",
      slug: "peercoin",
      logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/5.png",
      subreddit: "peercoin",
      notice: "",
      tags: [
        "mineable",
        "hybrid-pow-pos",
        "sha-256",
        "medium-of-exchange",
        "store-of-value",
        "payments",
        "staking",
      ],
      "tag-names": [
        "Mineable",
        "Hybrid - PoW & PoS",
        "SHA-256",
        "Medium of Exchange",
        "Store Of Value",
        "Payments",
        "Staking",
      ],
      "tag-groups": [
        "OTHERS",
        "ALGORITHM",
        "ALGORITHM",
        "INDUSTRY",
        "CATEGORY",
        "INDUSTRY",
        "CATEGORY",
      ],
      urls: {
        website: ["http://www.peercoin.net"],
        twitter: ["https://twitter.com/PeercoinPPC"],
        message_board: ["https://talk.peercoin.net"],
        chat: ["https://t.me/peercoin", "https://discord.gg/m294ReV"],
        facebook: [],
        explorer: [
          "https://chainz.cryptoid.info/ppc/",
          "https://explorer.peercoin.net/",
          "https://etherscan.io/token/0x044d078F1c86508e13328842Cc75AC021B272958",
          "https://polygonscan.com/token/0x91E7E32C710661C44ae44D10Aa86135d91C3Ed65",
        ],
        reddit: ["https://reddit.com/r/peercoin"],
        technical_doc: ["https://docs.peercoin.net/"],
        source_code: ["https://github.com/peercoin/peercoin"],
        announcement: ["https://bitcointalk.org/index.php?topic=101820.0"],
      },
      platform: {
        id: "1027",
        name: "Ethereum",
        slug: "ethereum",
        symbol: "ETH",
        token_address: "0x044d078F1c86508e13328842Cc75AC021B272958",
      },
      date_added: "2013-04-28T00:00:00.000Z",
      twitter_username: "PeercoinPPC",
      is_hidden: 0,
      date_launched: null,
      contract_address: [
        {
          contract_address: "0x044d078F1c86508e13328842Cc75AC021B272958",
          platform: {
            name: "Ethereum",
            coin: {
              id: "1027",
              name: "Ethereum",
              symbol: "ETH",
              slug: "ethereum",
            },
          },
        },
        {
          contract_address: "0x91E7E32C710661C44ae44D10Aa86135d91C3Ed65",
          platform: {
            name: "Polygon",
            coin: {
              id: "3890",
              name: "Polygon",
              symbol: "MATIC",
              slug: "polygon",
            },
          },
        },
      ],
      self_reported_circulating_supply: null,
      self_reported_tags: null,
      self_reported_market_cap: null,
    },
    6: {
      id: 6,
      name: "Novacoin",
      symbol: "NVC",
      category: "coin",
      description:
        "Novacoin (NVC) is a cryptocurrency launched in 2013. Users are able to generate NVC through the process of mining. Novacoin has a current supply of 2,335,756.713897. The last known price of Novacoin is 0.01479904 USD and is down -20.59 over the last 24 hours. It is currently trading on 1 active market(s) with $0.00 traded over the last 24 hours. More information can be found at https://nova-coin.org.",
      slug: "novacoin",
      logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/6.png",
      subreddit: "NovacoinCommunity/",
      notice: "",
      tags: ["mineable", "hybrid-pow-pos", "scrypt"],
      "tag-names": ["Mineable", "Hybrid - PoW & PoS", "Scrypt"],
      "tag-groups": ["OTHERS", "ALGORITHM", "ALGORITHM"],
      urls: {
        website: ["https://nova-coin.org", "https://novacoin.one"],
        twitter: [],
        message_board: [],
        chat: ["https://discord.gg/6juXnsSkGa", "https://t.me/NovaCoin_RU"],
        facebook: [],
        explorer: [
          "https://explorer.novaco.in/",
          "https://novacoin.ru/explorer/",
          "http://nvc-explorer.ewmcx.info/",
        ],
        reddit: ["https://reddit.com/r/NovacoinCommunity/"],
        technical_doc: ["https://github.com/novacoin-project/novacoin/wiki"],
        source_code: ["https://github.com/novacoin-project/novacoin"],
        announcement: ["https://bitcointalk.org/index.php?topic=5189560.0"],
      },
      platform: {
        id: "1839",
        name: "BNB",
        slug: "bnb",
        symbol: "BNB",
        token_address: "0xbf84720097de111a80f46f9d077643967042841a",
      },
      date_added: "2013-04-28T00:00:00.000Z",
      twitter_username: "",
      is_hidden: 0,
      date_launched: "2013-02-05T00:00:00.000Z",
      contract_address: [
        {
          contract_address: "0xbf84720097de111a80f46f9d077643967042841a",
          platform: {
            name: "BNB Smart Chain (BEP20)",
            coin: { id: "1839", name: "BNB", symbol: "BNB", slug: "bnb" },
          },
        },
      ],
      self_reported_circulating_supply: null,
      self_reported_tags: null,
      self_reported_market_cap: null,
    },
    7: {
      id: 7,
      name: "Devcoin3",
      symbol: "DVC",
      category: "coin",
      description:
        "Devcoin3 (DVC) is a cryptocurrency . Users are able to generate DVC through the process of mining. Devcoin3 has a current supply of 15,167,257,500. The last known price of Devcoin3 is 0.00002298 USD and is up 0.00 over the last 24 hours. More information can be found at http://devcoin.org.",
      slug: "devcoin",
      logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/7.png",
      subreddit: "devcoin",
      notice: "",
      tags: ["mineable"],
      "tag-names": ["Mineable"],
      "tag-groups": ["OTHERS"],
      urls: {
        website: ["http://devcoin.org"],
        twitter: ["https://twitter.com/devtome"],
        message_board: [],
        chat: [],
        facebook: [],
        explorer: ["http://node1.devcoin.cloud"],
        reddit: ["https://reddit.com/r/devcoin"],
        technical_doc: [],
        source_code: ["https://github.com/devcoin/core"],
        announcement: ["https://bitcointalk.org/index.php?topic=233997.0"],
      },
      platform: null,
      date_added: "2013-04-28T00:00:00.000Z",
      twitter_username: "devtome",
      is_hidden: 0,
      date_launched: null,
      contract_address: [],
      self_reported_circulating_supply: null,
      self_reported_tags: null,
      self_reported_market_cap: null,
    },
  },
};

export default async function handler(req, res) {
  try {
    const response = await axios.get(
      `https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest`,
      {
        params: req.query,
        headers: {
          "X-CMC_PRO_API_KEY": process.env.COIN_MARKET_CAP_API_KEY,
        },
      }
    );

    return res.status(200).json(response.data);
  } catch (err) {
    return res.status(500).json(err);
  }
}
